#!/bin/bash
./omake clean
./omake virboot328
./omake lilypad
./omake lilypad_resonator
./omake pro8
./omake pro16
./omake pro20
./omake diecimila
./omake ng
./omake arduinobt168
./omake atmega328
./omake atmega328_pro8
./omake sanguino
./omake mega
./omake atmega8
./omake atmega88
./omake luminet
./omake bluec88_19200
./omake bluec88_115200
./omake bluec328_19200
./omake bluec328_115200

