#!/bin/bash
./omake clean
./omake virboot328
./omake lilypad
./omake lilypad_resonator
./omake pro8
./omake pro16
./omake pro20
./omake diecimila
./omake ng
./omake mega
./omake atmega8
./omake atmega88
./omake atmega328
./omake atmega328_pro8
./omake luminet
./omake sanguino
./omake bluec88
./omake bluec328

